# We use the generated html to prevent issues involving markdown frontmatter

[[input.files]]
path = "./posts/2022/07/my-progress-so-far/index.html"
url = "https://ankitaS11.github.io/posts/2022/07/my-progress-so-far/"
title = "My Progress so far"

[[input.files]]
path = "./posts/2022/06/outreachy/index.html"
url = "https://ankitaS11.github.io/posts/2022/06/outreachy/"
title = "Outreachy"

[[input.files]]
path = "./posts/2022/06/outreachy-discussion-mongodb-vs-cosmosdb/index.html"
url = "https://ankitaS11.github.io/posts/2022/06/outreachy-discussion-mongodb-vs-cosmosdb/"
title = "Outreachy Discussion: MongoDB vs CosmosDB"

[[input.files]]
path = "./posts/2022/06/outreachy-starting-as-an-intern/index.html"
url = "https://ankitaS11.github.io/posts/2022/06/outreachy-starting-as-an-intern/"
title = "Outreachy: Starting as an intern"

[[input.files]]
path = "./posts/2021/10/product-of-an-array-except-self/index.html"
url = "https://ankitaS11.github.io/posts/2021/10/product-of-an-array-except-self/"
title = "Product of an array except self"

[[input.files]]
path = "./posts/2021/09/python-itertools.product/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-itertools.product/"
title = " Python - itertools.product()"

[[input.files]]
path = "./posts/2021/09/python-itertools.chain/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-itertools.chain/"
title = "Python - itertools.chain()"

[[input.files]]
path = "./posts/2021/09/basics-of-gans-and-loss-function/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/basics-of-gans-and-loss-function/"
title = "Basics of GANs and Loss Function"

[[input.files]]
path = "./posts/2021/09/python-decorators/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-decorators/"
title = "Python Decorators"

[[input.files]]
path = "./posts/2021/09/iterators-and-generators-in-python/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/iterators-and-generators-in-python/"
title = "Iterators and Generators in Python"

[[input.files]]
path = "./posts/2021/09/understanding-__-str-__-and-__-repr-__-in-python/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/understanding-__-str-__-and-__-repr-__-in-python/"
title = "Understanding __ str __( ) and  __ repr __( ) in Python"

[[input.files]]
path = "./posts/2021/09/vectors-in-c-/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/vectors-in-c-/"
title = "Vectors in C&#43;&#43;"

[[input.files]]
path = "./about/index.html"
url = "https://ankitaS11.github.io/about/"
title = "About"

[[input.files]]
path = "./posts/1/01/index.html"
url = "https://ankitaS11.github.io/posts/1/01/"
title = ""

[[input.files]]
path = "./posts/1/01/index.html"
url = "https://ankitaS11.github.io/posts/1/01/"
title = ""

[[input.files]]
path = "./categories/index.html"
url = "https://ankitaS11.github.io/categories/"
title = "Categories"

