# We use the generated html to prevent issues involving markdown frontmatter

[[input.files]]
path = "./posts/2022/06/mongodb-vs-cosmosdb/index.html"
url = "https://ankitaS11.github.io/posts/2022/06/mongodb-vs-cosmosdb/"
title = "MongoDB vs CosmosDB"

[[input.files]]
path = "./posts/2022/06/outreachy-introduce-yourself/index.html"
url = "https://ankitaS11.github.io/posts/2022/06/outreachy-introduce-yourself/"
title = "Outreachy | Introduce Yourself"

[[input.files]]
path = "./posts/2021/10/product-of-an-array-except-self/index.html"
url = "https://ankitaS11.github.io/posts/2021/10/product-of-an-array-except-self/"
title = "Product of an array except self"

[[input.files]]
path = "./posts/2021/09/python-itertools.product/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-itertools.product/"
title = " Python - itertools.product()"

[[input.files]]
path = "./posts/2021/09/python-itertools.chain/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-itertools.chain/"
title = "Python - itertools.chain()"

[[input.files]]
path = "./posts/2021/09/basics-of-gans-and-loss-function/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/basics-of-gans-and-loss-function/"
title = "Basics of GANs and Loss Function"

[[input.files]]
path = "./posts/2021/09/python-decorators/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/python-decorators/"
title = "Python Decorators"

[[input.files]]
path = "./posts/2021/09/iterators-and-generators-in-python/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/iterators-and-generators-in-python/"
title = "Iterators and Generators in Python"

[[input.files]]
path = "./posts/2021/09/understanding-__-str-__-and-__-repr-__-in-python/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/understanding-__-str-__-and-__-repr-__-in-python/"
title = "Understanding __ str __( ) and  __ repr __( ) in Python"

[[input.files]]
path = "./posts/2021/09/vectors-in-c-/index.html"
url = "https://ankitaS11.github.io/posts/2021/09/vectors-in-c-/"
title = "Vectors in C&#43;&#43;"

[[input.files]]
path = "./about/index.html"
url = "https://ankitaS11.github.io/about/"
title = "About"

[[input.files]]
path = "./posts/1/01/index.html"
url = "https://ankitaS11.github.io/posts/1/01/"
title = ""

[[input.files]]
path = "./posts/1/01/index.html"
url = "https://ankitaS11.github.io/posts/1/01/"
title = ""

[[input.files]]
path = "./categories/index.html"
url = "https://ankitaS11.github.io/categories/"
title = "Categories"

